frontend/controllers/BlogController.php
<?php

namespace frontend\controllers;


use common\models\ar\Post;
use common\models\ar\PostComment;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class BlogController extends Controller
{

    public $defaultAction = 'list';

    public function actionList()
    {
        $posts = Post::find()->actual()->published()->sortByDate()->all();
        return $this->render('list', ['posts' => $posts]);
    }

    public function actionPost($slug)
    {
        $post = Post::find()->slug($slug)->actual()->published()->one();
        $post->updateCounters(['views' => 1]);

        if ( !$post )
            throw new NotFoundHttpException();

        $commentModel = new PostComment();

        if ( $commentModel->load(\Yii::$app->request->post()) ) {
            $commentModel->post_id = $post->id;
            if ( !\Yii::$app->user->isGuest )
                $commentModel->user_id = \Yii::$app->user->id;
            if ( $commentModel->save() )
                return $this->redirect(\Yii::$app->request->url);
        }

        $comments = PostComment::buildTree($post->getComments()
            ->with('author')
            ->active()
            ->dateSort()
            ->asArray()
            ->all());

        return $this->render('post', [
            'post' => $post,
            'commentModel' => $commentModel,
            'comments' => $comments
        ]);
    }

}

frontend/views/blog/_list_item.php
<?php

/* @var \yii\web\View $this */
/* @var \common\models\ar\Post $post */

?>

<div class="col-lg-3 col-md-4 col-sm-6">
    <article class="article-list__col">
        <?= \yii\helpers\Html::img($post->image_preview); ?>
        <div class="article-list__contain">
            <div class="article-list__soc">
                <div class="ttl">Поделиться:</div>
                <ul>
                    <li>
                        <a class="vk" href=""></a>
                    </li>
                    <li>
                        <a class="tw" href=""></a>
                    </li>
                    <li>
                        <a class="fb" href=""></a>
                    </li>
                    <li>
                        <a class="gp" href=""></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="article-list__bottom-el">
            <div class="ttl text-center"><?= $post->title; ?></div>
            <?= \yii\helpers\Html::a('Читать', ['blog/post', 'slug' => $post->slug], ['class' => 'btn-10']); ?>
        </div>
    </article>
</div>

frontend/views/blog/_list_item_wide.php
<?php

use yii\helpers\Html;

/* @var \yii\web\View $this */
/* @var \common\models\ar\Post $post */


?>

<div class="col-lg-6 col-md-8 col-sm-12 article-list__long">
    <article class="article-list__col article-list__long-left">
        <img src="<?= $post->image_preview; ?>" alt="">
        <div class="article-list__contain">
        </div>
        <div class="article-list__bottom-el">
            <div class="ttl text-center">
                <?= Html::a($post->title, ['blog/post', 'slug' => $post->slug]); ?>
            </div>
            <?= Html::a('Читать', ['blog/post', 'slug' => $post->slug], ['class' => 'btn-10']); ?>
        </div>
    </article>
    <article class="article-list__col no-img-bg dark article-list__long-right">
        <div class="article-list__contain">
            <div class="article-list__soc">
                <div class="ttl">Поделиться:</div>
                <ul class="black-icon">
                    <li>
                        <a class="vk" href=""></a>
                    </li>
                    <li>
                        <a class="tw" href=""></a>
                    </li>
                    <li>
                        <a class="fb" href=""></a>
                    </li>
                    <li>
                        <a class="gp" href=""></a>
                    </li>
                </ul>
            </div>
            <div class="article-list__prew-text text-left">
                Первые три-четыре недели самые ленивые - пусть отращивает. Это позволит выявить любые неоднородные области, а длины волоса уже будет достаточно, чтобы подобрать самый неожиданный бородатый стиль. Скорее всего, при отращивании бороды Ваш мужчина столкнется
                с зудом и шелушением кожи. Именно поэтому Вы должны убедиться, что он держится
            </div>
        </div>
    </article>
</div>

frontend/views/blog/_post_comment.php
<?php

/* @var \yii\web\View $this */
/* @var array $comment */


//strftime('%e %b %G', $comment['comment']['created_at'])
?>

<li>
    <div class="img">
        <a href=""><img src="../images/img-17.jpg" alt=""></a>
    </div>
    <div class="txt">
        <div class="top-txt">
            <?php if ( $comment['comment']['author'] ): ?>
                <a class="name" href="#"><?= $comment['comment']['author']['firstname']
                    . ' ' . $comment['comment']['author']['lastname'] ?></a>
            <?php else: ?>
                <span class="name"><?= $comment['comment']['author_name'] ?></span>
            <?php endif; ?>
            <span class="time-status"><?= Yii::$app->formatter->asDate($comment['comment']['created_at']); ?></span>
        </div>
        <p><?= $comment['comment']['content']; ?></p>
        <ul class="icon-list">
            <li><a data-toggle="answer-comment" data-id="<?= $comment['comment']['id']; ?>"
                   href="javascript:void(0)" >
                    <i class="ico-answer active"></i></a></li>
        </ul>
    </div>
    <?php if ( count($comment['childs']) ) : ?>
        <ul>
            <?php foreach ($comment['childs'] as $child): ?>
                <?= $this->render('_post_comment', ['comment' => $child]); ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</li>

frontend/views/blog/list.php
<?php

/* @var \yii\web\View $this */
/* @var \common\models\ar\Post[] $posts */

$this->params['bodyOptions'] = [
    'class' => 'body-color-grey'
];

$this->registerJs("$('.article-list__bottom-el').on('click', function() {
    window.location = $(this).find('a').attr('href');
})");

?>

<div class="container article-list">
    <div class="row">

        <?php foreach ($posts as $post): ?>
        <?= $this->render($post->display_type == $post::DISPLAY_DEFAULT
                ? '_list_item' : '_list_item_wide', ['post' => $post]); ?>
        <?php endforeach; ?>

    </div>
    <div class="article-list__pagination">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-left">
                <a class="prev" href=""><i></i>Предидущие</a>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 text-right">
                <a class="next" href=""><i></i>Следующие</a>
            </div>
        </div>
    </div>
</div>

frontend/views/blog/post.php
<?php

/* @var \yii\web\View $this */
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var \common\models\ar\Post $post */
/* @var \common\models\ar\PostComment $commentModel */
/* @var array $comments */

?>
<section class="blog-post">
    <div class="container">
        <div class="blog-post__baner">
            <img src="<?= $post->image; ?>" alt="">
            <i class="ico-close"></i>
            <div class="row blog-post__baner-text">
                <div class="col-lg-8 col-md-8 blog-post__baner-title">
                    <div class="blog-post__icon-inf">
                        <ul>
                            <li><i class="ico-day"></i>2 дня назад</li>
                            <li><i class="ico-views"></i><?= $post->views; ?></li>
                            <li><i class="ico-comm"></i><?= count($comments); ?></li>
                        </ul>
                    </div>
                    <h1 class="blog-post__main-title"><?= $post->title; ?></h1>
                </div>
                <div class="article-list__soc">
                    <ul>
                        <li>
                            <a class="vk" href=""></a>
                        </li>
                        <li>
                            <a class="tw" href=""></a>
                        </li>
                        <li>
                            <a class="fb" href=""></a>
                        </li>
                        <li>
                            <a class="gp" href=""></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="blog-post__main-information">
            <div class="blog-post__main-text">
                <?= $post->content; ?>
            </div>
            <aside class="blog-post__sidebar hidden-sm">
                <div class="sidebar__ttl text-center">также читайте:</div>
                <div class="article-list">
                    <div class="article-list__col">
                        <img src="images/img-07.jpg" alt="">
                        <div class="article-list__contain">
                            <div class="article-list__soc">
                                <div class="ttl">Поделиться:</div>
                                <ul>
                                    <li>
                                        <a class="vk" href=""></a>
                                    </li>
                                    <li>
                                        <a class="tw" href=""></a>
                                    </li>
                                    <li>
                                        <a class="fb" href=""></a>
                                    </li>
                                    <li>
                                        <a class="gp" href=""></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="article-list__bottom-el">
                            <div class="ttl text-center">Как правильно ухаживать за бородой своего мужика</div>
                            <a class="btn-01" href="">Читать</a>
                        </div>
                    </div>
                    <div class="article-list__col">
                        <img src="images/img-07.jpg" alt="">
                        <div class="article-list__contain">
                            <div class="article-list__soc">
                                <div class="ttl">Поделиться:</div>
                                <ul>
                                    <li>
                                        <a class="vk" href=""></a>
                                    </li>
                                    <li>
                                        <a class="tw" href=""></a>
                                    </li>
                                    <li>
                                        <a class="fb" href=""></a>
                                    </li>
                                    <li>
                                        <a class="gp" href=""></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="article-list__bottom-el">
                            <div class="ttl text-center">Как правильно ухаживать за бородой своего мужика</div>
                            <a class="btn-01" href="">Читать</a>
                        </div>
                    </div>
                </div>
                <div class="blog-post__banner-sidebar">
                    <a href=""><img src="images/img-16.jpg" alt=""></a>
                </div>
            </aside>
        </div>
        <div class="blog-post__comments">
            <div class="blog-post__comments-text">
                <div class="blog-post__ttl-mob text-center visible-sm">Комментарии:</div>
                <ul class="comment-list">
                    <?php foreach ($comments as $comment): ?>
                        <?= $this->render('_post_comment', ['comment' => $comment]) ?>
                    <?php endforeach; ?>
                </ul>
                <div class="answer-form">
                    <?php $form = ActiveForm::begin([
                        'enableClientValidation' => FALSE
                    ]); ?>
                    <fieldset>
                        <?= Html::activeHiddenInput($commentModel, 'parent_id',
                            ['id' => 'comment_parent']); ?>
                        <?php if ( Yii::$app->user->isGuest ): ?>
                            <div class="row">
                                <div class="col-md-6">
                                    <?= $form->field($commentModel, 'author_name')
                                        ->textInput(['placeholder' => 'Ваше имя'])
                                        ->label(FALSE); ?>
                                </div>
                                <div class="col-md-6">
                                    <?= $form->field($commentModel, 'author_email')
                                        ->textInput(['placeholder' => 'Ваш Email'])
                                        ->label(FALSE); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <?= $form->field($commentModel, 'content')
                            ->textarea(['rows' => 10, 'cols' => 10])->label(FALSE); ?>
                        <div class="btn-box">
                            <span class="btn-12">отмена</span>
                            <input class="btn-11" type="submit" value="Ответить">
                        </div>
                    </fieldset>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
            <div class="blog-post__comments-form">
                <div class="blog-post__form">
                    <form action="">
                        <fieldset>
                            <div class="ttl text-center">Оставить отзыв</div>
                            <input class="about-us__form-input" placeholder="Имя" type="text">
                            <input class="about-us__form-input" placeholder="Email" type="email">
                            <textarea class="about-us__form-input" name="massage" rows="8" cols="40" placeholder="Сообщение"></textarea>
                            <div class="text-right">
                                <input class="btn-02" value="Отправить" type="submit">
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>