backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\ar\ShopFaq;
use Yii;
use yii\base\Model;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use zxbodya\yii2\elfinder\ConnectorAction;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'elfinder' => array(
                'class' => ConnectorAction::className(),
                'settings' => array(
                    'root' => Yii::getAlias('@uploads/storage'),
                    //'URL' => Yii::getAlias('@web') . '/uploads',
                    'URL' => 'http://manly.local/uploads/storage/',//debug
                    'rootAlias' => 'Загрузки',
                    'mimeDetect' => 'none'
                )
            ),
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'elfinder'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/ShopController.php
<?php

namespace frontend\controllers;


use common\models\ar\Feedback;
use common\models\ar\ShopCategory;
use common\models\ar\ShopProduct;
use common\models\ar\ShopProductComment;
use common\queries\ShopProductCommentQuery;
use common\queries\ShopProductVarietyAttachmentQuery;
use common\queries\ShopProductVarietyQuery;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class ShopController extends Controller
{

    public function actionCatalog()
    {
        $categories = ShopCategory::find()->root()->active()->priority()->all();
        $products = ShopProduct::find()
            ->with(['varieties' => function ( $q ) {/* @var ShopProductVarietyQuery $q */
                $q->priority()->with(['attachments' => function ( $q2 ) {
                    /* @var ShopProductVarietyAttachmentQuery $q2 */
                    $q2->byPriority();
                }]);
            }])
            ->active()
            ->all();

        return $this->render('catalog', [
            'categories' => $categories,
            'products' => $products
        ]);
    }

    public function actionProduct($slug)
    {

        $model = ShopProduct::find()
            ->slug($slug)
            ->active()->one();

        if ( !$model )
            throw new NotFoundHttpException();

        $commentModel = new ShopProductComment();

        if ( $commentModel->load(\Yii::$app->request->post()) ) {
            $commentModel->shop_product_id = $model->id;
            if ( !\Yii::$app->user->isGuest )
                $commentModel->user_id = \Yii::$app->user->id;
            if ( $commentModel->save() )
                return $this->redirect(\Yii::$app->request->url);
        }

        $comments = ShopProductComment::buildTree($model->getComments()
            ->with('author')
            ->active()
            ->dateSort()
            ->asArray()
            ->all());

        $feedbackModel = new Feedback(['shop_product_id' => $model->id]);


        return $this->render('product', [
            'model' => $model,
            'commentModel' => $commentModel,
            'comments' => $comments,
            'feedbackModel' => $feedbackModel
        ]);

    }

    public function actionFaq($productSlug)
    {
        $model = ShopProduct::find()->slug($productSlug)->one()->faq;
        return $this->render('faq', [
            'model' => $model
        ]);
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\ar\Country;
use common\models\ar\Feedback;
use common\models\ar\Partner;
use common\models\ar\ShopCategory;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'feedback' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {

        $cats = ShopCategory::find()
            ->root()
            ->active()
            ->priority()
            ->landing()
            ->all();

        return $this->render('index', [
            'categories' => $cats
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionPartnersXml()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $partners = Partner::find()->priority()->asArray()->all();

        return $partners;
    }

    public function actionPartners()
    {
        $partners = Partner::find()->priority()->asArray()->all();

        $places = Country::find()->where(['IS NOT', 'gmap', NULL])
            ->with(['cities' => function ( $q ) {
                $q->andWhere(['IS NOT', 'gmap', NULL]);
            }])->asArray()->all();

        return $this->render('partners', [
            'partners' => $partners,
            'places' => $places
        ]);
    }

    public function actionFeedback()
    {
        $model = new Feedback();
        if ( $model->load(Yii::$app->request->post()) )
            $model->save();
        return $this->goBack(['site/index']);
    }
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

$this->title = 'About';
?>


<article class="about-us">
    <div class="about-us__images-sm visible-md">
        <div class="about-us__contacts white visible-xs">
            <div>
                <ul class="ico-soc-01 white">
                    <li>
                        <a class="vk" href=""></a>
                    </li>
                    <li>
                        <a class="tw" href=""></a>
                    </li>
                    <li>
                        <a class="fb" href=""></a>
                    </li>
                </ul>
            </div>
            <div>
                <a class="about-us__mail white" href="mailto:mail@mail.com">mail@mail.com</a>
            </div>
            <div>
                <a class="about-us__telephone white" href="tel:068 929-24-924">068 929-24-924</a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row about-us__top-row">
            <div class="col-lg-6 col-md-6 hidden-md">
                <div class="about-us__images"><img src="images/img-09.jpg" alt=""></div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="about-us__left-text">
                    <h1 class="about-us__ttl">меня зовут<strong>Владимир Дибчак</strong></h1>
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-6">
                            <p>MANLY club зиждется на трех принципах: минимализм, функциональность и доступность.<br> Первый легко просматривается в лаконичном дизайне, удобной и практичной таре, и, само собой, в экономном расходе продукта. </p>
                            <p>Второй - в 100% отдаче. Рецептура авторская, пропорции безупречны, составляющие натуральны и высочайшего качества (работаем с импортным сырьем, в основном из Германии). Итог: продукт “работает”, полностью выполняя поставленные перед ним задачи.<br>									Третий - тут без комментариев. Пройдите в раздел “магазин” и убедитесь сами.</p>
                            <blockquote>
                                Made by greasers,<br> approved by barbers!
                            </blockquote>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-6">
                            <p>Мы верны своим принципам, уважаем традиции и не боимся утверждать новые стандарты.<br> Stay MANLY with ‘MANLY club’<br> !Второй - в 100% отдаче. Рецептура авторская, пропорции безупречны, составляющие натуральны и высочайшего качества (работаем
                                с импортным сырьем, в основном из Германии). Итог: продукт “работает”, полностью выполняя поставленные перед ним задачи. Третий - тут без комментариев. Пройдите в раздел “магазин” и убедитесь сами.</p>
                            <img src="images/img-10.jpg" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="about-us__information">
                    <div class="about-us__ttl hidden-xs">вы можете<strong>связаться со мной</strong></div>
                    <div class="row about-us__contacts hidden-xs">
                        <div class="col-lg-4 col-md-4">
                            <ul class="ico-soc-01">
                                <li>
                                    <a class="vk" href=""></a>
                                </li>
                                <li>
                                    <a class="tw" href=""></a>
                                </li>
                                <li>
                                    <a class="fb" href=""></a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <a class="about-us__mail" href="mailto:mail@mail.com">mail@mail.com</a>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <a class="about-us__telephone" href="tel:068 929-24-924">068 929-24-924</a>
                        </div>
                    </div>
                    <p>Если у вас есть вопросы или предложения, вы можете связаться со мной через социальные сети, позвонить по телефону или написать на почту заполнив форму.</p>
                    <p>Всегда рад вашим предложениям!</p>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="about-us__form">
                    <form action="">
                        <fieldset>
                            <div class="row">
                                <div class="col-lg-6 col-md-6 margin-bottom-sm">
                                    <input type="text" class="about-us__form-input" placeholder="Имя">
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <input type="email" class="about-us__form-input" placeholder="Email">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-12 col-md-12">
                                    <textarea class="about-us__form-input" name="massage" rows="8" cols="40" placeholder="Сообщение"></textarea>
                                </div>
                            </div>
                            <div class="text-right">
                                <input class="btn-02" type="submit" value="Отправить">
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</article>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;

/* @var $categories \common\models\ar\ShopCategory[] */

$this->title = 'Manly Club - Главная';

$this->params['bodyOptions'] = [
    'class' => 'home-page'
];
$this->params['showVideoHead'] = TRUE;

?>

<section class="brand-holder" id="brand-holder">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 col-lg-offset-6 col-md-offset-6">
                <div class="ttl-01">Бренд №1 в Украине</div>
                <div class="big-first-letter">
                    <div class="big-first-letter__mob-hidden">
                        <p> Тебя с гордостью приветствует команда “MANLY”, производящая натуральные средства для усов, бород и волос (с 2015 года и для тату).</p>
                        <p>Наша история берет свое начало с февраля 2014 года, ведь именно тогда, в городе Харьков, был основан первый подобный украинским локальный бренд, MANLY club.</p>
                        <p>Вдохновившись винтажной эстетикой, возрожденными знаниями и утилитаризмом, мы создали оригинальный продукт, придающий мужскому стилю большей элегантности и лоска, а дизайн служит отдушиной для настоящих педантов и мужчин, живущих атмосферой старой
                            школы. Производство и фасовка происходит вручную, так что с гордостью заявляем – «TOTALLY HANDMADE» </p>
                        <p>Мы всегда изготавливаем нашу продукцию небольшими партиями. И дело не только в том, чтобы обеспечить высокое качество и постоянство товара, но и потому что мы получаем огромное удовольствие разрабатывая и создавая его. </p>
                        <p>Мы действительно верим в наш продукт и пользуемся им каждый день. Поэтому нет ни малейшего сомнения, что Вы получите истинное наслаждение пользуясь им.</p>
                        <p>Stay MANLY with MANLY club!</p>
                    </div>
                    <div class="text-center">
                        <span class="btn-04 visible-xs">РАЗВЕРНУТЬ</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="main-category">
    <div class="container">
        <div class="ttl-02"><span>категории</span></div>
    </div>
    <div class="main-category__items">
        <div class="row">
            <?php foreach ( $categories as $category ): ?>
            <div class="col col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="bg-img">
                    <img src="<?= $category->image; ?>" alt="">
                </div>
                <div class="bg-img__box-inf">
                    <div class="bg-img__box-inf-in">
                        <img src="<?= $category->image; ?>" alt="">
                    </div>
                </div>
                <div class="col__ttl"><?= $category->landing_name ? : $category->name; ?></div>
                <ul class="col__btn-list">
                    <li><span class="col__btn-ico ico-02"></span></li>
                    <li>
                        <?= Html::a('', ['shop/catalog'], ['class' => 'col__btn-ico ico-01']) ?>
                    </li>
                </ul>
                <div class="col__box-inf">
                    <ul class="col__btn-list-box">
                        <li>
                            <?= Html::a('', ['shop/catalog'], ['class' => 'col__btn-ico ico-01']) ?>
                        </li>
                        <li><span class="col__btn-ico ico-02"></span></li>
                    </ul>
                    <div class="col__ttl-box">
                        <?= $category->name; ?>
                    </div>
                    <p><?= $category->description; ?></p>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>
<div class="video-main">
    <i class="video-main__play-btn"></i>
    <img src="images/img-06.jpg" alt="">
</div>
<sectoin class="article-list">
    <div class="container">
        <div class="ttl-02"><span>Последние статьи</span></div>
        <div class="text-center">
            <p>Вже давно відомо, що читабельний зміст буде заважати зосередитись людині, яка оцінює<br> композицію сторінки.<br> </p>
            <p>Сенс використання Lorem Ipsum полягає в тому, що цей текст має більш-менш нормальне розподілення<br> літер на відміну від, наприклад, "Тут іде текст. Тут іде текст." Це робить текст схожим на </p>
        </div>
        <div class="blog__item-slider">
            <div class="item">
                <article class="article-list__col">
                    <img src="images/img-07.jpg" alt="">
                    <div class="article-list__contain">
                        <div class="article-list__soc">
                            <div class="ttl">Поделиться:</div>
                            <ul>
                                <li>
                                    <a class="vk" href=""></a>
                                </li>
                                <li>
                                    <a class="tw" href=""></a>
                                </li>
                                <li>
                                    <a class="fb" href=""></a>
                                </li>
                                <li>
                                    <a class="gp" href=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="article-list__bottom-el">
                        <div class="ttl">Как правильно ухаживать за бородой своего мужика</div>
                        <a class="btn-10" href="">Читать</a>
                    </div>
                </article>
            </div>
            <div class="item">
                <article class="article-list__col">
                    <img src="images/img-07.jpg" alt="">
                    <div class="article-list__contain">
                        <div class="article-list__soc">
                            <div class="ttl">Поделиться:</div>
                            <ul>
                                <li>
                                    <a class="vk" href=""></a>
                                </li>
                                <li>
                                    <a class="tw" href=""></a>
                                </li>
                                <li>
                                    <a class="fb" href=""></a>
                                </li>
                                <li>
                                    <a class="gp" href=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="article-list__bottom-el">
                        <div class="ttl">Как правильно ухаживать за бородой своего мужика</div>
                        <a class="btn-10" href="">Читать</a>
                    </div>
                </article>
            </div>
            <div class="item">
                <article class="article-list__col">
                    <img src="images/img-07.jpg" alt="">
                    <div class="article-list__contain">
                        <div class="article-list__soc">
                            <div class="ttl">Поделиться:</div>
                            <ul>
                                <li>
                                    <a class="vk" href=""></a>
                                </li>
                                <li>
                                    <a class="tw" href=""></a>
                                </li>
                                <li>
                                    <a class="fb" href=""></a>
                                </li>
                                <li>
                                    <a class="gp" href=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="article-list__bottom-el">
                        <div class="ttl">Как правильно ухаживать за бородой своего мужика</div>
                        <a class="btn-10" href="">Читать</a>
                    </div>
                </article>
            </div>
            <div class="item">
                <article class="article-list__col">
                    <img src="images/img-07.jpg" alt="">
                    <div class="article-list__contain">
                        <div class="article-list__soc">
                            <div class="ttl">Поделиться:</div>
                            <ul>
                                <li>
                                    <a class="vk" href=""></a>
                                </li>
                                <li>
                                    <a class="tw" href=""></a>
                                </li>
                                <li>
                                    <a class="fb" href=""></a>
                                </li>
                                <li>
                                    <a class="gp" href=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="article-list__bottom-el">
                        <div class="ttl">Как правильно ухаживать за бородой своего мужика</div>
                        <a class="btn-10" href="">Читать</a>
                    </div>
                </article>
            </div>
        </div>
    </div>
</sectoin>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/partners.php
<?php

use frontend\assets\PartnersAsset;

/* @var \yii\web\View $this */
/* @var array $partners */
/* @var array $places */

PartnersAsset::register($this);

?>

<div style="display: none;" id="partners_json"><?= json_encode($partners); ?></div>
<div style="display: none;" id="places_json"><?= json_encode($places); ?></div>
<div class="partners-page">
    <div class="partners-page__map">
        <div class="partners-page__select-wrap text-center">
            <div class="container">
                <select id="select_country" class="basic">
                </select>
                <div class="long-list">
                    <select id="select_city" class="basic"></select>
                </div>
            </div>
        </div>
        <div id="mapstyle"></div>
        <div class="partners-page__slider-wrap">
            <div class="container">
                <div id="partners-slider" class="partners-page__slider">
                    <?php foreach ($partners as $partner): ?>
                        <div class="item" data-map-pos="<?= $partner['gmap']; ?>" >
                            <img src="/uploads/partners/<?= $partner['img']; ?>" alt="">
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>